config/routes.rb
Rails.application.routes.draw do

  resources :activities

  root 'welcome#index'

  devise_for :beneficiaries, controllers: { registrations: 'beneficiaries/registrations'}
  devise_for :donors, controllers: { registrations: 'donors/registrations'}

  resources :beneficiaries, only: ['index','show'] do
    resources :requested_resources do
      resources :claimed_resources, only: ['create']
    end
  end

  resources :donors, only: ['show']

  get 'how_it_works' => 'how_it_works#index'

end

app/models/beneficiary.rb
class Beneficiary < ActiveRecord::Base

  has_many :requested_resources

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, :address, :contact_name, :contact_number, :email, presence: true
  validates :name, uniqueness: true
  has_many :requested_resources

  def count_donors
    # self.requested_resources[0].claimed_resources[0].donor
    list_of_donors = [];
    self.requested_resources.each do |resource|
      resource.claimed_resources.each do |claimed|
        list_of_donors << claimed.donor.id
      end
    end
    list_of_donors.uniq.length
  end

  def all_fulfilled?
    if self.requested_resources.find_by(fulfilled: false)
      return false
    else
      return true
    end
  end

end

app/controllers/beneficiaries/registrations_controller.rb
class Beneficiaries::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    address = resource.address.gsub(" ", "+")
    response = HTTParty.get("https://maps.googleapis.com/maps/api/geocode/json?address=#{address}&key=#{ENV['GEOCODE_KEY']}")
    body = JSON.parse(response.body)
    coordinates = body["results"][0]["geometry"]["location"]
    resource.update_attributes(longitude: coordinates["lng"], latitude: coordinates["lat"], password: sign_up_params["password"])
    Keen.publish(:sign_ups, { type: 'beneficiary'})
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/beneficiaries_controller.rb
class BeneficiariesController < ApplicationController

	def index
	  @beneficiaries = Beneficiary.all
    if request.xhr?
      render :json => @beneficiaries
    end
	end

	def show
		@beneficiary = Beneficiary.find(params[:id])
		if request.xhr?
			render json: @beneficiary, :include => :requested_resources
		end
	end

end

app/helpers/beneficiaries_helper.rb
module BeneficiariesHelper
end

app/views/beneficiaries/index.html.erb
<div class="container">

<div class="search-bar">
  <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
  <input class="beni-search-text" type="text" placeholder="Find a Beneficiary">
</div>

<h4>Search By</h4>
<form action="" method="">
  <input type="checkbox" name="vehicle" value="In Need of Donors"> In Need of Donors<br>
  <input type="checkbox" name="vehicle" value="In Need of Resources"> In Need of Resources<br>
</form>
  <div class="row">
    <!-- <div class="col-lg-2 col-md-2"></div> -->
    <div class="col-lg-12 col-md-12">


      <table class="table">
        <tr class="table-head">
          <td>Name</td>
          <td># of Requested Resources</td>
          <td># of Donors</td>
          <td>Contact Information</td>
        </tr>
        <% @beneficiaries.each do |beneficiary| %>
          <tr class="beni-row">
            <td class="beni-name"><%= beneficiary.name %></td>
            <td><%= beneficiary.requested_resources.where(fulfilled: false).count %></td>
            <td><%= beneficiary.count_donors %> </td>
            <td> <%= link_to("Contact", beneficiary) %> </td>
          </tr>
        <% end %>

    </tbody>
  </table>
    <div class="no-results alert alert-danger">No Search Results Found</div>
  </div>

  </div>
</div>

app/views/beneficiaries/show.html.erb
<div class="row">

	<div class="col-md-6">
		<h3 class="beneficiary-header">Organization</h3>
		<p><strong>Organization Name:</strong>	<%= @beneficiary.name %></p>
		<p><strong>Description:</strong> <%= @beneficiary.description %></p>
		<% if @beneficiary == current_beneficiary %>
			<%= link_to "Change Password", edit_beneficiary_registration_path(@beneficiary), class: "btn btn-primary" %>
		<% end %>
	</div>

	<div class="col-md-6">
		<h3 class="beneficiary-header">Contact Info</h3>
		<p><strong>Contact Name:</strong> <%= @beneficiary.contact_name %></p>
		<p><strong>Contact Number:</strong> <%= @beneficiary.contact_number %></p>
		<p><strong>Email:</strong> <%= @beneficiary.email %></p>
		<p><strong>Address:</strong> <%= @beneficiary.address %></p>
	</div>

</div>

<div id="beneficiary-map" data-lat="<%= @beneficiary.latitude %>" data-long="<%= @beneficiary.longitude %>"></div>
<% if @beneficiary.all_fulfilled? || @beneficiary.requested_resources.empty? %>
	<h4>They have no open requests.</h4>
<% else %>
<h3 style="text-align: center;">Current Needs</h3>
	<table class="table">
	  <tr>
	    <th>Item Name</th>
	    <th>Quantity Needed</th>
	    <th>Quantity Claimed</th>
	    <th>Urgency</th>
	    <th>Notes</th>
	    <th>&nbsp;</th>
	  </tr>
	  <% @beneficiary.requested_resources.each do |resource|  %>
	  	<% next if resource.fulfilled %>
	    <tr id="<%= resource.id %>">
	      <td class="resource-name"><%= resource.name %></td>
	      <td class="resource-quantity"><%= resource.quantity %></td>
	      <td class="resource-quantity-claimed"><%= resource.quantity_claimed %></td>
	      <td class="resource-urgency"><%= resource.urgency %></td>
	      <td class="resource-notes"><%= resource.notes if resource.notes %></td>
	      <% if current_donor %>
	      <td>
	        <a href="/beneficiaries/<%= resource.beneficiary_id %>/requested_resources/<%=resource.id %>"><button class="btn btn-primary">Claim</button></a>
	      </td>
	      <% else %>
	      <td>
	      	<a href="/donors/sign_in">
	      		<button class="btn btn-info">Login To Claim</button>
	      	</a>
	      </td>
	      <% end %>
	    </tr>
	  <% end %>
	</table>
<% end %>