config/routes.rb
Rails.application.routes.draw do

  resources :activities

  root 'welcome#index'

  devise_for :beneficiaries, controllers: { registrations: 'beneficiaries/registrations'}
  devise_for :donors, controllers: { registrations: 'donors/registrations'}

  resources :beneficiaries, only: ['index','show'] do
    resources :requested_resources do
      resources :claimed_resources, only: ['create']
    end
  end

  resources :donors, only: ['show']

  get 'how_it_works' => 'how_it_works#index'

end

app/models/beneficiary.rb
class Beneficiary < ActiveRecord::Base

  has_many :requested_resources

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, :address, :contact_name, :contact_number, :email, presence: true
  validates :name, uniqueness: true
  has_many :requested_resources

  def count_donors
    # self.requested_resources[0].claimed_resources[0].donor
    list_of_donors = [];
    self.requested_resources.each do |resource|
      resource.claimed_resources.each do |claimed|
        list_of_donors << claimed.donor.id
      end
    end
    list_of_donors.uniq.length
  end

  def all_fulfilled?
    if self.requested_resources.find_by(fulfilled: false)
      return false
    else
      return true
    end
  end

end

app/models/claimed_resource.rb
class ClaimedResource < ActiveRecord::Base
  belongs_to :donor
  belongs_to :requested_resource
end

app/models/donor.rb
class Donor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :claimed_resources
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, :country, presence: true
end

app/models/requested_resource.rb
class RequestedResource < ActiveRecord::Base

  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_beneficiary }

  # creates call backs for activity record


  has_many :claimed_resources
	belongs_to :beneficiary
	validates :name, :quantity, :urgency, presence: true

  def quantity_remaining
    amount_left = self.quantity
    self.claimed_resources.each do |resource|
      amount_left -= resource.quantity
    end
    amount_left
     # = self.quantity - self.claimed_resources[0].quantity
  end

  def quantity_claimed
    self.quantity - self.quantity_remaining
  end

  def fulfilled?
    quantity_claimed >= quantity
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = PublicActivity::Activity.order("created_at desc")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include PublicActivity::StoreController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_devise_permitted_parameters, if: :devise_controller?


  protected

  def configure_devise_permitted_parameters
    registration_params = [:name, :email, :password, :password_confirmation, :phone, :country, :address, :latitude, :longitude, :contact_name, :contact_number, :description]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) {
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) {
        |u| u.permit(registration_params)
      }
    end
  end


end

app/controllers/beneficiaries_controller.rb
class BeneficiariesController < ApplicationController

	def index
	  @beneficiaries = Beneficiary.all
    if request.xhr?
      render :json => @beneficiaries
    end
	end

	def show
		@beneficiary = Beneficiary.find(params[:id])
		if request.xhr?
			render json: @beneficiary, :include => :requested_resources
		end
	end

end

app/controllers/claimed_resources_controller.rb
class ClaimedResourcesController < ApplicationController

  def create
    requested_resource = RequestedResource.find(params[:requested_resource_id])
    claimed_resource = ClaimedResource.new(claimed_resource_params)
    if claimed_resource.save!
      current_donor.claimed_resources << claimed_resource
      requested_resource.claimed_resources << claimed_resource
      if requested_resource.fulfilled?
        requested_resource.update_attributes(fulfilled: true)
      end
    end
    redirect_to beneficiary_requested_resource_path(requested_resource.beneficiary, requested_resource)
  end

  private

  def claimed_resource_params
    params.require(:claimed_resource).permit(:quantity)
  end

end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController

  def show
  	@donor = Donor.find(params[:id])
		redirect_to root_path unless @donor == current_donor
  end

end

app/controllers/how_it_works_controller.rb
class HowItWorksController < ApplicationController
  def index
  end
end

app/controllers/requested_resources_controller.rb
class RequestedResourcesController < ApplicationController

  def index
    @requested_resource = RequestedResource.all
  end

  def show
    @requested_resource = RequestedResource.find(params[:id])
  end

  def new
    @resource = RequestedResource.new()
    beneficiary = Beneficiary.find(params[:beneficiary_id])
    redirect_to root_path unless current_beneficiary == beneficiary
  end

  def destroy
    p params
    RequestedResource.find(params[:id]).destroy
    redirect_to new_beneficiary_requested_resource_path(current_beneficiary)
  end

  def update

    resource = RequestedResource.find(params[:beneficiary_id])
    if params[:fulfilled] == 'Yes'
      fulfilled = true
      Keen.publish(:resource_request, {fulfilled: true})
    else
      fulfilled = false
    end
    resource.update_attributes(
      name: params[:name],
      quantity: params[:quantity],
      urgency: params[:urgency],
      notes: params[:notes],
      fulfilled: fulfilled
      )

    render json: resource

  end

  def create
    resource = RequestedResource.new(resource_params)
    if resource.save
      current_beneficiary.requested_resources << resource
      Keen.publish(:resource_request, {fulfilled: false})
      redirect_to new_beneficiary_requested_resource_path(current_beneficiary)
    else
      redirect_to new_beneficiary_requested_resource_path(current_beneficiary)
    end
  end


  private

  def resource_params
    params.require(:requested_resource).permit(:name, :quantity, :urgency, :notes, :fulfilled)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/activities_helper.rb
module ActivitiesHelper

  def time_calc(created_at)

      time_now = Time.now.to_i
      time_reference = DateTime.parse(created_at).strftime('%s').to_i
      elapsed_time = time_now - time_reference

      case elapsed_time
        when 0 then 'just now'
        when 1 then 'a second ago'
        when 2..59 then '%d seconds ago' % elapsed_time.to_s
        when 60..119 then 'a minute ago' #120 = 2 minutes
        when 120..3540 then '%d minutes ago' % (elapsed_time/60).to_i.to_s
        when 3541..7100 then 'an hour ago' # 3600 = 1 hour
        when 7101..82800 then  '%d hours ago' % ((elapsed_time+99)/3600).to_i.to_s
        when 82801..172000 then 'a day ago' # 86400 = 1 day
        when 172001..518400 then  '%d days ago' % ((elapsed_time+800)/(60*60*24)).to_i.to_s
        when 518400..1036800 then 'a week ago'
        else '%d weeks ago' % ((elapsed_time+180000)/(60*60*24*7)).to_i.to_s

      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beneficiaries_helper.rb
module BeneficiariesHelper
end

app/helpers/claimed_resources_helper.rb
module ClaimedResourcesHelper
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/helpers/how_it_works_helper.rb
module HowItWorksHelper
end

app/helpers/requested_resources_helper.rb
module RequestedResourcesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_alerts.html.erb
  <% if flash[:notice] %>
    <p class="alert alert-success alert-dismissible" role="alert"><%= notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </p>
  <% elsif flash[:alert] %>
    <p class="alert alert-danger alert-dismissible" role="alert"><%= alert %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </p>
  <% end %>

app/views/layouts/_nav_update.html.erb
<nav id ="topnav" class = "navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id ="navbar-padding-override" class="collapse navbar-collapse">
      <ul id ="nav-items" class="nav navbar-nav">
        <li class="nav_li"><%= link_to "See The Need", root_path %></li>
        <li class="nav_li"><a href="#about">About</a></li>
        <li class="nav_li"><%= link_to 'News Feed', activities_path %></li>
        <li class="nav_li"><%= link_to "View Needs", beneficiaries_path %>
        <% if beneficiary_signed_in? %>
        <li class="nav_li">
          <%= link_to "Manage my Needs", new_beneficiary_requested_resource_path(current_beneficiary) %>
        </li>
        <% end %>
        <li class="nav_li"><%= link_to 'How it Works', how_it_works_path %></li>
      </ul>

        <ul class="nav navbar-nav navbar-right">
          <% unless donor_signed_in? || beneficiary_signed_in? %>
          <li class="dropdown">
            <a href="#" id ="dropdown-nav" class="dropdown-toggle" data-toggle="dropdown"> Log in <b class="caret"></b></a>
            <ul class="dropdown-menu" role="menu">
              <li><a  href="/donors/sign_in">I Can Help</a></li>
              <li><a id="organization_modal_trigger" href="/beneficiaries/sign_in">I Need Help</a></li>
            </ul>
          </li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if donor_signed_in? %>
          <li><%= link_to("Signed in as #{current_donor.name}", current_donor) %></li>
          <li><%= link_to('Logout', destroy_donor_session_path) %></li>
          <% elsif beneficiary_signed_in? %>
          <li><%= link_to("Signed in as #{current_beneficiary.name}", current_beneficiary) %></li>
          <li><%= link_to('Logout', destroy_beneficiary_session_path) %></li>
          <% end %>

          <% unless donor_signed_in? || beneficiary_signed_in? %>
          <li class="dropdown">
            <a href="#" id ="dropdown-nav" class="dropdown-toggle" data-toggle="dropdown"> Register <b class="caret"></b></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/donors/sign_up">I Can Help</a></li>
              <li><a href="/beneficiaries/sign_up">I Need Help</a></li>
            </ul>
          </li>
          <% end %>
        </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<!-- <html class="no-js"> -->
<!--<![endif]-->
<html>
<head>
  <title>See The Need</title>

  <link href='https://fonts.googleapis.com/css?family=Oswald|Roboto+Condensed:700,400|Roboto' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.2/handlebars.min.js"></script>
  <script src='https://api.tiles.mapbox.com/mapbox.js/v2.1.9/mapbox.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox.js/v2.1.9/mapbox.css' rel='stylesheet' />
  <script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/leaflet.markercluster.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.css' rel='stylesheet' />
  <link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.Default.css' rel='stylesheet' />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<body>

<div class="container">

  <%= render 'layouts/nav_update' %>
  <%= render 'layouts/alerts' %>


  <%= yield %>
</div>

</body>
</html>